export const RECEIVE_INFO = 'RECEIVE_INFO';
export const FETCHING_INFO  = 'FETCHING_INFO ';
export const RECEIVE_HOME = 'RECEIVE_HOME';
export const FETCHING_HOME  = 'FETCHING_HOME ';
export const RECEIVE_HEROES = 'RECEIVE_HEROES';
export const RECEIVE_PARTNERS = 'RECEIVE_PARTNERS';
